---
# This YAML configuration specifies a server with two volumes and two users
server:
  instance_type: t2.micro
  ami_type: ami-0e4035ae3f70c400f
  architecture: x86_64
  root_device_type: ebs
  virtualization_type: hvm
  min_count: 1
  max_count: 1
  KeyName: devops_automation
  volumes:
    - device: /dev/xvdf
      size_gb: 10
      type: gp2
      mount: /
    - device: /dev/xvdg
      size_gb: 1
      type: gp2
      mount: /data
  users:
    - login: username1
      ssh_key: --user1 ssh public key goes here-- user1@localhost
    - login: username2
      ssh_key: --user2 ssh public key goes here-- user2@localhost
